import React, { useState } from 'react';
import { 
  Calculator, 
  DollarSign, 
  Scale, 
  FileText, 
  Download, 
  CheckCircle2, 
  Sparkles, 
  TrendingUp, 
  HelpCircle,
  Landmark,
  ShieldAlert,
  Award
} from 'lucide-react';
import confetti from 'canvas-confetti';
import { federalCircuitsBenchmark, landmarkSettlementPrecedents } from '../../data/settlementCalculatorData';

export default function SettlementCalculatorView({ showToast }) {
  // Calculator Inputs
  const [selectedCircuitId, setSelectedCircuitId] = useState('cir-7');
  const [claimType, setClaimType] = useState('lethal'); // 'lethal' | 'severe_injury' | 'false_arrest' | 'first_amendment'
  const [hasVideoCorroboration, setHasVideoCorroboration] = useState(true);
  const [hasPriorBradyDisciplinaryHistory, setHasPriorBradyDisciplinaryHistory] = useState(true);
  const [hasMonellSupervisoryFailure, setHasMonellSupervisoryFailure] = useState(true);
  const [medicalExpenses, setMedicalExpenses] = useState(250000);
  const [punitiveMultiplier, setPunitiveMultiplier] = useState(2.5);

  const selectedCircuit = federalCircuitsBenchmark.find(c => c.id === selectedCircuitId) || federalCircuitsBenchmark[0];

  // Base Calculation Engine
  const calculateEstimatedDamages = () => {
    let baseCompensatory = 0;
    if (claimType === 'lethal') baseCompensatory = 8000000;
    else if (claimType === 'severe_injury') baseCompensatory = 2500000;
    else if (claimType === 'false_arrest') baseCompensatory = 450000;
    else baseCompensatory = 200000;

    let multiplier = selectedCircuit.severityMultiplier;
    if (hasVideoCorroboration) multiplier += 0.35;
    if (hasPriorBradyDisciplinaryHistory) multiplier += 0.40;
    if (hasMonellSupervisoryFailure) multiplier += 0.50;

    const totalCompensatory = (baseCompensatory + Number(medicalExpenses)) * multiplier;
    const estimatedPunitive = totalCompensatory * (punitiveMultiplier * 0.4);
    const statutoryAttorneyFees = (totalCompensatory + estimatedPunitive) * 0.25;
    const totalValuation = totalCompensatory + estimatedPunitive + statutoryAttorneyFees;

    return {
      compensatory: Math.round(totalCompensatory),
      punitive: Math.round(estimatedPunitive),
      attorneyFees: Math.round(statutoryAttorneyFees),
      total: Math.round(totalValuation)
    };
  };

  const valuation = calculateEstimatedDamages();

  const handleExportValuationReport = () => {
    const reportText = `================================================================================
JUSTICE PULSE — SECTION 1983 CIVIL RIGHTS DAMAGES & SETTLEMENT VALUATION REPORT
VALUATION DATE: ${new Date().toLocaleString()}
JURISDICTION: ${selectedCircuit.name.toUpperCase()}
CLAIM CLASSIFICATION: ${claimType.toUpperCase()}
================================================================================

I. ESTIMATED DAMAGES BREAKDOWN:
- Economic & Compensatory Damages: $${valuation.compensatory.toLocaleString()}
- Exemplary & Punitive Damages: $${valuation.punitive.toLocaleString()}
- Statutory 42 U.S.C. § 1988 Attorney Fees: $${valuation.attorneyFees.toLocaleString()}
--------------------------------------------------------------------------------
TOTAL PROJECTED SETTLEMENT VALUATION RANGE:
$${valuation.total.toLocaleString()} USD
--------------------------------------------------------------------------------

II. FORENSIC AGGRAVATING VALUATION FACTORS:
- Video/Bodycam Corroboration: ${hasVideoCorroboration ? 'CONFIRMED (+35% Multiplier)' : 'None'}
- Prior Brady Officer Disciplinary Record: ${hasPriorBradyDisciplinaryHistory ? 'CONFIRMED (+40% Multiplier)' : 'None'}
- Monell Municipal Supervisory Custom: ${hasMonellSupervisoryFailure ? 'CONFIRMED (+50% Multiplier)' : 'None'}
- Circuit Multiplier: ${selectedCircuit.severityMultiplier}x

III. HISTORICAL COMPARABLE JURISDICTIONAL PRECEDENTS:
${landmarkSettlementPrecedents.map(p => `• ${p.caseName} (${p.year}): ${p.amount} — ${p.keyFactors}`).join('\n')}

================================================================================
Generated by Justice Pulse Civil Rights Legal Analytics Valuation Engine
================================================================================`;

    const element = document.createElement('a');
    const file = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    element.href = URL.createObjectURL(file);
    element.download = `SETTLEMENT_VALUATION_REPORT_${selectedCircuit.id.toUpperCase()}.TXT`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);

    confetti({ particleCount: 45, spread: 65 });
    showToast('Certified Settlement Valuation Report downloaded!', 'success');
  };

  return (
    <div className="space-y-6 select-none">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-emerald-950/70 to-slate-900 rounded-3xl p-6 border border-emerald-800/50 shadow-2xl flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2 text-emerald-400 mb-1">
            <Calculator className="w-5 h-5 animate-pulse" />
            <span className="text-xs font-bold uppercase tracking-wider font-mono">Civil Rights Damages Estimator</span>
          </div>
          <h2 className="text-xl sm:text-2xl font-black text-white font-display">
            Section 1983 Settlement & Damages Valuation Calculator
          </h2>
          <p className="text-xs text-slate-300 max-w-2xl mt-1 leading-relaxed">
            Estimate projected settlement values, compensatory damages, and Monell multipliers across all 11 Federal Judicial Circuits based on historical jury verdicts and precedent settlements.
          </p>
        </div>

        <button
          onClick={handleExportValuationReport}
          className="px-5 py-2.5 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white rounded-xl text-xs font-bold shadow-glow-emerald flex items-center gap-1.5 transition-all flex-shrink-0"
        >
          <Download className="w-4 h-4" />
          <span>Export Valuation Report</span>
        </button>
      </div>

      {/* Main Grid: Calculator Inputs & Projected Damages Output */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Input Parameters (6 Cols) */}
        <div className="lg:col-span-6 bg-slate-900/90 backdrop-blur-md rounded-3xl border border-slate-800 p-6 space-y-4 shadow-2xl">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300 flex items-center gap-2 font-mono border-b border-slate-800 pb-3">
            <Scale className="w-4 h-4 text-emerald-400" />
            <span>Valuation Parameters</span>
          </h3>

          <div>
            <label className="block text-xs font-bold uppercase text-slate-400 mb-1">Federal Judicial Circuit</label>
            <select
              value={selectedCircuitId}
              onChange={(e) => setSelectedCircuitId(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-emerald-500 font-semibold"
            >
              {federalCircuitsBenchmark.map(c => (
                <option key={c.id} value={c.id}>{c.name} (Benchmark Avg: {c.historicalAvgLethal})</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-xs font-bold uppercase text-slate-400 mb-1">Claim Type</label>
            <select
              value={claimType}
              onChange={(e) => setClaimType(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-emerald-500 font-semibold"
            >
              <option value="lethal">Fatal Lethal Force / Loss of Life (42 U.S.C. § 1983)</option>
              <option value="severe_injury">Severe Physical Injury / Taser / Canine Trauma</option>
              <option value="false_arrest">Unlawful Detention & False Imprisonment</option>
              <option value="first_amendment">First Amendment Filming Retaliation & Seizure</option>
            </select>
          </div>

          <div>
            <label className="block text-xs font-bold uppercase text-slate-400 mb-1">Direct Medical & Economic Hard Costs ($)</label>
            <input
              type="number"
              value={medicalExpenses}
              onChange={(e) => setMedicalExpenses(Math.max(0, parseInt(e.target.value) || 0))}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-emerald-500 font-mono"
            />
          </div>

          <div>
            <label className="block text-xs font-bold uppercase text-slate-400 mb-1">
              Punitive Multiplier ({punitiveMultiplier}x)
            </label>
            <input
              type="range"
              min="1"
              max="5"
              step="0.5"
              value={punitiveMultiplier}
              onChange={(e) => setPunitiveMultiplier(parseFloat(e.target.value))}
              className="w-full accent-emerald-500 cursor-pointer h-2 bg-slate-950 rounded-lg"
            />
          </div>

          {/* Aggravating Factor Checkboxes */}
          <div className="space-y-2 pt-2 border-t border-slate-800">
            <p className="text-[10px] font-mono text-slate-400 uppercase font-bold">Aggravating Forensic Multipliers:</p>

            <label className="flex items-center space-x-2.5 p-2.5 bg-slate-950 rounded-xl border border-slate-800/80 cursor-pointer hover:border-slate-700">
              <input
                type="checkbox"
                checked={hasVideoCorroboration}
                onChange={(e) => setHasVideoCorroboration(e.target.checked)}
                className="rounded accent-emerald-500 w-4 h-4"
              />
              <span className="text-xs text-slate-200">Unredacted Bodycam / Eyewitness Video Corroboration (+35%)</span>
            </label>

            <label className="flex items-center space-x-2.5 p-2.5 bg-slate-950 rounded-xl border border-slate-800/80 cursor-pointer hover:border-slate-700">
              <input
                type="checkbox"
                checked={hasPriorBradyDisciplinaryHistory}
                onChange={(e) => setHasPriorBradyDisciplinaryHistory(e.target.checked)}
                className="rounded accent-emerald-500 w-4 h-4"
              />
              <span className="text-xs text-slate-200">Prior Concealed Disciplinary / Brady Offense Record (+40%)</span>
            </label>

            <label className="flex items-center space-x-2.5 p-2.5 bg-slate-950 rounded-xl border border-slate-800/80 cursor-pointer hover:border-slate-700">
              <input
                type="checkbox"
                checked={hasMonellSupervisoryFailure}
                onChange={(e) => setHasMonellSupervisoryFailure(e.target.checked)}
                className="rounded accent-emerald-500 w-4 h-4"
              />
              <span className="text-xs text-slate-200">Monell Failure-to-Screen & Municipal Custom (+50%)</span>
            </label>
          </div>
        </div>

        {/* Right: Projected Valuation Display Card (6 Cols) */}
        <div className="lg:col-span-6 bg-slate-900/90 backdrop-blur-md rounded-3xl border border-slate-800 p-6 sm:p-8 space-y-6 shadow-2xl flex flex-col justify-between">
          <div className="space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <span className="text-xs font-bold uppercase tracking-wider text-emerald-300 font-mono flex items-center gap-1.5">
                <TrendingUp className="w-4 h-4" /> Projected Settlement Valuation
              </span>
              <span className="text-[10px] text-slate-400 font-mono bg-slate-950 px-2 py-0.5 rounded border border-slate-800">
                Rule 408 Protected
              </span>
            </div>

            {/* Big Projected Total Card */}
            <div className="p-6 bg-gradient-to-br from-slate-950 via-emerald-950/40 to-slate-950 rounded-2xl border-2 border-emerald-500/50 shadow-2xl text-center space-y-1">
              <span className="text-[11px] font-mono text-emerald-400 uppercase tracking-wider font-bold">
                Total Estimated Claim Value
              </span>
              <h3 className="text-3xl sm:text-4xl font-black text-white font-mono tracking-tight">
                ${valuation.total.toLocaleString()}
              </h3>
              <p className="text-[11px] text-slate-400 font-mono">
                Projected Valuation Range based on {selectedCircuit.name}
              </p>
            </div>

            {/* Breakdown Bars */}
            <div className="space-y-2.5 text-xs font-mono">
              <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 flex items-center justify-between">
                <span className="text-slate-400">Compensatory Damages:</span>
                <span className="text-white font-bold">${valuation.compensatory.toLocaleString()}</span>
              </div>

              <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 flex items-center justify-between">
                <span className="text-slate-400">Punitive Damages:</span>
                <span className="text-amber-400 font-bold">${valuation.punitive.toLocaleString()}</span>
              </div>

              <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 flex items-center justify-between">
                <span className="text-slate-400">Statutory Attorney Fees (§ 1988):</span>
                <span className="text-indigo-400 font-bold">${valuation.attorneyFees.toLocaleString()}</span>
              </div>
            </div>
          </div>

          {/* Precedent Benchmarks */}
          <div className="p-4 bg-slate-950 rounded-2xl border border-slate-800 space-y-2">
            <h5 className="text-[11px] font-mono text-slate-300 font-bold uppercase flex items-center gap-1">
              <Award className="w-3.5 h-3.5 text-amber-400" /> Landmark Federal Precedents:
            </h5>
            <div className="space-y-1.5 text-[11px] text-slate-400">
              {landmarkSettlementPrecedents.slice(0, 3).map((p, idx) => (
                <div key={idx} className="flex items-center justify-between border-b border-slate-900 pb-1">
                  <span className="truncate max-w-[220px] text-slate-300">{p.caseName}</span>
                  <span className="font-mono text-emerald-400 font-bold">{p.amount}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
